"""
Contain the code allowing the plots of the paper "Modeling framework unifying contact and social networks" to be drawn.
Note that the schemas, tables, etc. are not included as they could be generated by hand.
"""

import os
import sys
ROOT_DIR = os.path.dirname(__file__)
sys.path.append(ROOT_DIR)

import Librairies.Temp_net as tp
from Librairies.centered_motifs import draw_10_CTN, get_NCTN_to_weight

import matplotlib.pyplot as plt

def figure6():
	list_ref_name = ['conf16', 'utah']
	list_refs = [tp.XP_name(ref_name) for ref_name in list_ref_name]

	xp_name = 'conf16'
	xp_tij = tp.XP_name(xp_name).load_TN()
	temp_net = tp.Temp_net(xp_tij)
	#convert the t_ij data into a sequence of graphs (temporal network), stored in temp_net.TN
	temp_net.get_TN()

	depth = 3
	NCTN_to_weight = get_NCTN_to_weight(temp_net.TN, depth)

	fig, ax = draw_10_CTN(CTN_to_weight, depth, starting_rank=0, normalize=True, choice="NCTN")
	plt.show()

if __name__ == '__main__':
	pass
