"""
Contain the code allowing the plots of the paper "Modeling framework unifying contact and social networks" to be drawn.
Note that the schemas, tables, etc. are not included as they could be generated by hand.
"""

import os, sys
ROOT_DIR = os.path.dirname(os.path.dirname(__file__))
sys.path.append(ROOT_DIR)
from libs.temporal_network import Table_interaction
from libs.centered_motifs import draw_10_CTN, get_NCTN_to_weight
import matplotlib.pyplot as plt
import numpy as np
from libs.models.tuning import get_ref_data


def analyze_refs():
	"""
	define the reference temporal networks, compute the readable parameters for each one of them
	and save these data in data/analysis/refs/<ref_name>/readable_params.txt
	Also compute the reference observables (used for fitness computation) and save them in data/analysis/refs/<ref_name>/ref_obs.txt
	"""
	# decide of the refs
	ref_names = ["conf16", "conf17", "highschool3", "utah", "work2"]

	ref_dir_in = os.path.join(ROOT_DIR, "data", "temporal_networks", "formatted")
	ref_dir_out = os.path.join(ROOT_DIR, "data", "analysis", "refs")

	# first compute the readable parameters of each reference
	for ref_name in ref_names:
		os.makedirs(os.path.join(ref_dir_out, ref_name), exist_ok=True)

		ref = tp.Temp_net(np.loadtxt(os.path.join(ref_dir_in, ref_name + ".txt"), dtype=int))
		get_ref_data(ref, ref_name=ref_name, ref_dir_out=ref_dir_out)

def tune_models():
	"""
	define the models considered and their hyperparameters, and tune each model instance with respect to the references
	then save the best parameters, the evolution of the fitness over the generations, the hyperparameters of the genetic algorithm
	and the best genome
	data are saved at data/analysis/tuned/
	"""
	pass

def get_metric_tensor():
	"""
	compute the metric tensor between each tuned model and its references
	then save the data at data/analysis/metric_tensor/
	"""
	pass

def generate_data():
	"""
	generate the data needed to compute the figures:
	- the tuned models wrt the empirical references
	- the metric tensor
	"""

def figure6():
	list_ref_name = ['conf16', 'utah']
	list_refs = [tp.XP_name(ref_name) for ref_name in list_ref_name]

	xp_name = 'conf16'
	xp_tij = tp.XP_name(xp_name).load_TN()
	temp_net = tp.Temp_net(xp_tij)
	#convert the t_ij data into a sequence of graphs (temporal network), stored in temp_net.TN
	temp_net.get_TN()

	depth = 3
	NCTN_to_weight = get_NCTN_to_weight(temp_net.TN, depth)

	fig, ax = draw_10_CTN(CTN_to_weight, depth, starting_rank=0, normalize=True, choice="NCTN")
	plt.show()

if __name__ == '__main__':
	pass
